backend:
  name: github
  repo: DaleJorden/deaterfoundation
  branch: main

media_folder: "src/static/img"
public_folder: "/static/img"

# publish_mode: editorial_workflow
collections:
  - label: "Pages"
    name: "pages"
    editor:
      preview: false
    files:
      - label: "About Page"
        name: "about"
        file: "src/about.html"
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Home Page"
        name: "home"
        file: "src/index.html"
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Path", name: "path", widget: "hidden", default: "home" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Registry Page"
        name: "registry"
        file: "src/registry.html"
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Funding Page"
        name: "funding"
        file: "src/funding.html"
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Contact Page"
        name: "contact"
        file: "src/contact.html"
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Researchers Page"
        name: "researchers"
        file: "src/researchers.html"
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  - label: "Blog"
    name: "blog"
    folder: "src/posts"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["Tags", "created", "from", "config.yml"]

  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "navigation"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }

      - label: "Site Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: "Site Name", name: name, widget: string }
          - { label: "Tagline", name: tagline, widget: string }
          - { label: "Author", name: author, widget: string }
          - { label: "URL", name: url, widget: string }
          - label: "Contact Information"
            name: contact
            widget: object
            fields:
              - { label: "Organization", name: organization, widget: string }
              - { label: "Address Line 1", name: address_line1, widget: string }
              - { label: "City", name: address_city, widget: string }
              - { label: "State", name: address_state, widget: string }
              - { label: "Zip Code", name: address_zip, widget: string }
              - { label: "Email", name: email, widget: string }
          - label: "Social Media"
            name: social
            widget: object
            fields:
              - { label: "Facebook URL", name: facebook, widget: string }
          - label: "Footer Information"
            name: footer
            widget: object
            fields:
              - { label: "Copyright Text", name: copyright, widget: string }
              - { label: "Candid Rating Text", name: candid_rating, widget: text }
              - { label: "UMass Chan Text", name: umass_text, widget: text }
